---
networks:
  n2:
    name: n2
    external: true
  n3:
    name: n3
    external: true
  air:
    name: air
    external: true
services:
  gnb:
    container_name: gnb
    hostname: gnb
    image: 5gdeploy.localhost/srsran4g
    command: ["/entrypoint.sh", "5g_gnb"]
    environment:
      AMF_N2_IP: 192.168.12.20
      GNB_N2_IP: 192.168.12.50
      GNB_N3_IP: 192.168.13.50
      GNB_ID: '1001'
      MCC: '001'
      MNC: '01'
      TAC: '117'
    init: true
    cap_add:
      - IPC_LOCK
      - NET_ADMIN
      - SYS_NICE
    networks:
      n2:
        ipv4_address: 192.168.12.50
      n3:
        ipv4_address: 192.168.13.50
      air:
        ipv4_address: 192.168.10.50
    volumes:
      - type: bind
        source: ./logs
        target: /srsran-log
  ue:
    container_name: ue
    hostname: ue
    image: 5gdeploy.localhost/srsran4g
    command: ["/entrypoint.sh", "5g_ue"]
    environment:
      USIM_IMSI: '001011234567896'
      USIM_K: '00000000000000000000000000000000'
      USIM_OP: ''
      USIM_OPC: '66E94BD4EF8A2C3B884CFA59CA342B2E'
      USIM_ALGO: milenage
      DNN: default
    init: true
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      air:
        ipv4_address: 192.168.10.55
    volumes:
      - type: bind
        source: ./logs
        target: /srsran-log
