---
networks:
  n2:
    name: n2
    external: true
  n3:
    name: n3
    external: true
  air:
    name: air
    external: true
services:
  gnb:
    container_name: gnb
    hostname: gnb
    image: 5gdeploy.localhost/ueransim
    command: ["/entrypoint.sh", "gnb"]
    environment:
      PLMN: '001-01'
      NCI: '000000010'
      GNBIDLEN: 32
      TAC: '000075'
      LINK_IP: 192.168.10.50
      NGAP_IP: 192.168.12.50
      GTP_IP: 192.168.13.50
      AMF_IPS: 192.168.12.20,192.168.12.21
      SLICES: 01,01000001,01D143A5,01000002
    init: true
    networks:
      n2:
        ipv4_address: 192.168.12.50
      n3:
        ipv4_address: 192.168.13.50
      air:
        ipv4_address: 192.168.10.50
  ue:
    container_name: ue
    hostname: ue
    image: 5gdeploy.localhost/ueransim
    command: ["/entrypoint.sh", "ue"]
    environment:
      PLMN: '001-01'
      IMSI: '001011234567896'
      KEY: '00000000000000000000000000000000'
      OPC: '66E94BD4EF8A2C3B884CFA59CA342B2E'
      GNB_IPS: 192.168.10.50
      SLICES: 01000001,01000002
      SESSIONS: default:01000001,internet:01000002
    init: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      air:
        ipv4_address: 192.168.10.55
